framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    templating:
        engines: ['twig']

    #https://stackoverflow.com/questions/70845276/monolog-elasticsearch-configuration-in-symfony
    #https://symfony.com/doc/4.x/http_client.html
    http_client:
        scoped_clients:
            es.client:
                base_uri: "%env(ELASTICSEARCH_HOST)%"
                auth_basic: "%env(ELASTICSEARCH_USER)%:%env(ELASTICSEARCH_PASS)%"