lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'Avat0' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600

    api_platform:
        check_path: /login_check
        username_path: username
        password_path: security.credentials.password